apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-poc
  template:
    metadata:
      labels:
        app: node-poc
    spec:
      containers:
      - name: node-poc
        image: localhost:8082/node-poc-image:latest
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: node-poc
spec:
  selector:
    app: node-poc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
